"""
Filter Lineage Extractor - Enhanced extractor for Filter operators.

Captures additional information specific to Filter operations:
- Filter rate (fraction of rows removed)
- Filter-specific stats column tracking
"""

from __future__ import annotations

from typing import Any, Optional, Set

from data_juicer.core.lineage.extractors.base import (
    BaseLineageExtractor,
    OperatorLineage,
)
from data_juicer.core.lineage.facets import (
    BaseFacet,
    PerformanceFacet,
)


class FilterStatsFacet(BaseFacet):
    """Facet capturing filter-specific statistics."""

    _schemaURL = 'https://datajuicer.com/schemas/filter-stats-facet.json'

    def __init__(
        self,
        rows_before: int = 0,
        rows_after: int = 0,
        rows_removed: int = 0,
        filter_rate: float = 0.0,
        stats_column: Optional[str] = None,
    ):
        super().__init__()
        self.rows_before = rows_before
        self.rows_after = rows_after
        self.rows_removed = rows_removed
        self.filter_rate = filter_rate
        self.stats_column = stats_column

    @classmethod
    def from_row_counts(
        cls,
        rows_before: int,
        rows_after: int,
        stats_column: Optional[str] = None,
    ) -> 'FilterStatsFacet':
        rows_removed = rows_before - rows_after
        filter_rate = rows_removed / rows_before if rows_before > 0 else 0.0
        return cls(
            rows_before=rows_before,
            rows_after=rows_after,
            rows_removed=rows_removed,
            filter_rate=round(filter_rate, 6),
            stats_column=stats_column,
        )


class FilterLineageExtractor(BaseLineageExtractor):
    """Extractor for Filter operators.

    Enhancements over default:
    - On complete: adds FilterStatsFacet with filter rate
    - Tracks the stats column generated by filter ops
    """

    @staticmethod
    def _get_stats_column(op: Any) -> Optional[str]:
        """Get the stats column name used by a filter op."""
        # Filter ops in Data-Juicer typically produce a stats column
        # named Fields.stats in the dataset
        stats_key = getattr(op, 'stats_export_path', None)
        if stats_key:
            return str(stats_key)
        return None

    def extract_on_complete(
        self,
        op: Any,
        columns_before: Optional[Set[str]] = None,
        columns_after: Optional[Set[str]] = None,
        row_count_before: Optional[int] = None,
        row_count_after: Optional[int] = None,
        duration: Optional[float] = None,
    ) -> OperatorLineage:
        """Extract lineage at filter completion.

        Adds filter-specific stats like filter rate.
        """
        lineage = super().extract_on_complete(
            op, columns_before, columns_after,
            row_count_before, row_count_after, duration,
        )

        # Add filter stats facet
        if row_count_before is not None and row_count_after is not None:
            stats_col = self._get_stats_column(op)
            lineage.run_facets['filterStats'] = FilterStatsFacet.from_row_counts(
                rows_before=row_count_before,
                rows_after=row_count_after,
                stats_column=stats_col,
            )

        return lineage
